# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb35964f05000f3caab18b43767a0ce34d368abfc967dce00acc3e61294eb5e16809864d60cfaa49f08ac29e0886f51d0d8b3ac74f2cab7a65c03a86f8ea4b69

test:
  secret_key_base: 14cfbe35047aea421ce1408c457e40ab5d829b093abe99911a3b69acf0f6b818e7e196ae8ef2acb41caecc647f353400fbf22d23abde2e527ef9c5bd67c41fa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 14cfbe35047aea421ce1408c457e40ab5d829b093abe99911a3b69acf0f6b818e7e196ae8ef2acb41caecc647f353400fbf22d23abde2e527ef9c5bd67c41fa7
